global:
  imageOverrides:
    assisted_image_service: ''
    assisted_installer: ''
    assisted_installer_agent: ''
    assisted_installer_controller: ''
    assisted_service: ''
    postgresql_12: ''
  pullPolicy: Always
  pullSecret: null
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
    operator: Exists
org: open-cluster-management
